config/routes.rb
Seatyourself::Application.routes.draw do
  get "users/new"
  get "users/edit"
  get "users/show"
  get "welcome_path" => "welcome#index"
  get '/users/:user_id/join/:id' => "users#joinnew"
  resources :sessions
  root "welcome#index"
  resources :users do
    resources :categories 
    resources :reservations
  end
  resources :restaurants do
    resources :moments
    resources :menus
  end
  resources :menus do
    resources :items
  end

  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  get '/sessions' => 'sessions#create'

  match '/users/:user_id/join/:id', to: "users#joinnew", via: [:get,:post]
  get '/users/:user_id/:restaurants_id/rate' => "restaurants#rate"
  get "/users/:id/time" => "restaurants#index"
  get "/users/:id/reserve" => "restaurants#reserve"
  get "/users/:user_id/:restaurant_id/:menu_id/:item_id" => "orders#create"
  get "/restaurants/:restaurant_id/:menu_id"=> "menus#show"
  get "/remove/:restaurant_id/:menu_id/:order_id/:id" => "orders#remove"
  

  

end

app/models/menu.rb
class Menu < ActiveRecord::Base
	belongs_to :restaurant
	has_many :items
	has_many :orders
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController


	def index
		@menus= Menu.all
	end

	def show

		if params[:id]
			@menu=Menu.find_by_id(params[:id])
		elsif
			@menu=Menu.find_by_id(params[:menu_id])
		end

		@rest=Restaurant.find_by_id(@menu.restaurant_id)
		@user=User.find_by_id(current_user)
		if @menu.orders!=[]
			@order=@menu.orders.where(user_id: current_user.id)[0]

			
		end
	end

	def edit
		@menu=menu.find_by_id(params[:id])
	end

	def new
		@rest=Restaurant.find_by_id(params[:restaurant_id])
		@menu=@rest.menus.build
	end

	def update
		@menu=menu.find_by_id(params[:id])
		if menu.update_attributes(menu_params)
			redirect_to menu_path(@res)
		else
			render 'edit'
		end
	end

	def create
		@rest=Restaurant.find_by_id(params[:restaurant_id])
		@menu=@rest.menus.build(menu_params)
				if @menu.save


			
			



					@rest.save


					
					redirect_to restaurant_menu_path(@rest,@menu)
		else

		flash[:error]="No submission buddy"
		redirect_to @rest
		
		end
	end

	def destroy
		@menu=menu.find_by_id(params[:id])
		@restaurant=Restaurant.find_by_id(menu.restaurant_id)


		@restaurant.save
		@menu.destroy
		redirect_to user_path(current_user)
	end


	private


	def menu_params
    params.require(:menu).permit(:season)
  end

end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/new.html.erb
<%= form_for [@rest,@menu] do |f| %>
  <% if @menu.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @menu.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :season %><br/>
    <%= f.text_field :season %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

<%= link_to "Home", @rest %>

app/views/menus/show.html.erb
<br>
<%=Restaurant.find_by_id(@menu.restaurant_id).name%>: <br>
Menu: <br>
<h6><%=@menu.season%></h6>

  <% if current_user.categories.find{|c| c[:text]=="owner"} %>
  <% @menu.items.each do |item| %>
  <%= item.product %> <br>
  <%= item.desc %> <br>
  <%= item.price %> <br>

  	<%= link_to "Delete item", menu_item_path(@menu,item), :confirm => "Delete?", :method => :delete %> <br>
  	<% end %>
  	<% end %>
  	 <% if current_user.categories.find{|c| c[:text]=="owner"} %>
  	<br><%=link_to "New Item", new_menu_item_path(@menu) %><br><br>
  	<%= link_to "Back to Restaurant", @rest %>
  	<% end %>
  

  
  <% if current_user.categories.find{|c| c[:text]=="ruser"} %>
  <% @menu.items.each do |item| %>
  <%= item.product %> <br>
  <%= item.desc %> <br>
  <%= item.price %> <br>
  	<%= link_to "Order", "/users/#{current_user.id}/#{@rest.id}/#{@menu.id}/#{item.id}" %> <br>

  <% end %>
  <br>
  <p>Your current order:<div> <% @order.items.each do |item| %>
  	                      <%= item.product %> | Price: <%= item.price %> | Quantity: <%= item.quantity %> <%= link_to "Remove item", "/remove/#{@menu.restaurant_id}/#{@menu.id}/#{@order.id}/#{item.id}" %><br>
  	                     </div><% end %>
  <% end %>
  


<br>
<div><%= link_to "Home", current_user %></div>