config/routes.rb
Seatyourself::Application.routes.draw do
  get "users/new"
  get "users/edit"
  get "users/show"
  get "welcome_path" => "welcome#index"
  get '/users/:user_id/join/:id' => "users#joinnew"
  resources :sessions
  root "welcome#index"
  resources :users do
    resources :categories 
    resources :reservations
  end
  resources :restaurants do
    resources :moments
    resources :menus
  end
  resources :menus do
    resources :items
  end

  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  get '/sessions' => 'sessions#create'

  match '/users/:user_id/join/:id', to: "users#joinnew", via: [:get,:post]
  get '/users/:user_id/:restaurants_id/rate' => "restaurants#rate"
  get "/users/:id/time" => "restaurants#index"
  get "/users/:id/reserve" => "restaurants#reserve"
  get "/users/:user_id/:restaurant_id/:menu_id/:item_id" => "orders#create"
  get "/restaurants/:restaurant_id/:menu_id"=> "menus#show"
  get "/remove/:restaurant_id/:menu_id/:order_id/:id" => "orders#remove"
  

  

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :categories
	has_many :reservations
	has_many :restaurants, :through=> :reservations
	has_many :orders
	has_many :items, :through=> :orders
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    debugger
  end
  def new
  	@user=User.new
    @categories=@user.categories.new
  end

  def joinnew
    @user=current_user
    @reservation=Reservation.new

    render 'joinnew'
  end

  def order
  end

  def joinncreate
    @user=User.find_by_id(params[:user_id])
    @reservation=@user.reservations.build(reservation_params)
    if @reservation_params.save
      redirect_to @user
    else
      render 'joinnew'
    end
  end

  def create
  	@user=User.new(user_params)
    save=true

    if params[:owner]==nil && params[:ruser]==nil
      save=false
    end
  	if @user.save && save
      if params[:ruser]

       @user.categories << Category.new({text:"ruser"})
    end
    if params[:owner] 
      @category=@user.categories

      @user.categories << Category.new({text:"owner"})
    end
  		redirect_to "/welcome_path", :notice => "Signed up!"
  	else
  		render "new"
  	end
  end

  def update
    @user=User.find_by_id(params[:id])
    save=true
    

    if params[:owner]==nil && params[:ruser]==nil
      save=false
    end
    if @user.update_attributes(user_params) && save
      if params[:ruser]
       @user.categories<< Category.new({text:"owner"})
    end
    if params[:owner] 
      @user.categories<< Category.new({text:"owner"})
    end
      redirect_to "/welcome_path", :notice => "Signed up!"
    else
      render "new"
    end
 
  end

  def edit
    @user=User.find_by_id(params[:id])
    @categories=@user.categories
  end

   def show
	@user=User.find(params[:id])
  @restaurantsown=[]
  if @user.categories.find{|c| c.text=="owner"}
    Restaurant.all.each do |rest|
      @restaurantsown << rest if rest.owner.to_i ==current_user.id

    end
  end
  @restaurantsown
  @restaurants=[]
  if @user.reservations!=[]
    Restaurant.all.each do |rest|

      @user.reservations.each do |rev|
        @restaurants << rest unless rev.restaurant_id==rest.id

      end
    end
  else
    @restaurants=Restaurant.all
  end

  @restaurants
  @reservations=@user.reservations
    
	session[:user_id]=@user.id

	end

  private
  def user_params
  	params.require(:user).permit(:email,:password, :password_confirmation, :name)
  end

  def reservation_params
    params.require(:reservation).permit(:hour,:user_id,:restaurant_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/joinnew.html.erb
<%= form_for [@user,@reservation] do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= Restaurant.find_by_id(params[:id]).name%>
  <div class="field">
    <%= f.label :hour %><br/>
    <%= f.datetime_field :hour %>
  </div>
  <% session[:restaurant_id]=params[:id].to_i%>
  </div>
   <div class="field">
    <%= f.label :day %><br/>
    <%= f.text_field :day %>
  </div>
   <div class="field">
    <%= f.label :numberofseats %><br/>
    <%= f.number_field :numberofseats %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>

<%= link_to "Home", @user %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= check_box_tag(:owner) %>
<%= label_tag(:owner, "I am a restuarant owner") %>
<%= check_box_tag(:ruser) %>
<%= label_tag(:ruser, "I am a restaurant eater") %>
  <div class="actions"><%= f.submit %></div>
<% end %>

<%= link_to "Home", root_url %>

app/views/users/show.html.erb
<h1><%=current_user.name%></h1>
<p>You are an <% current_user.categories[0..-1].each do |c| %>
	<%= c.text %> <br>
<% end %>
</p>
<% if current_user.categories.find{|c| c[:text]=="owner"} %>

	<h2> My restaurants </h2>
	

 	<ul class="large-block-grid-3"><% @restaurantsown.each do |r| %>
 		<li><h5><%=r.name %></h5>
  		Hours of Operation: <%=r.opentime.strftime("%H:%M") %>-<%= r.closetime.strftime("%H:%M") %> <br>
	Tables size: <%=r.tablesize %> <br>
	Number of tables: <%=r.tables %> <br>
	Total seats: <%= r.totalsize %> <br>
	Address: <%= r.address%> <br> 
	<%= link_to "New Menu", new_restaurant_menu_path(r) %><br>
	<p> Menus: <% r.menus.each do |menu| %>
		          <%=link_to "#{menu.season}", restaurant_menu_path(r,menu) %>
		        <% end %></p>
	
	<%= link_to "Time slots available for reservation", "/users/#{r.id}/time" %><br>
	<%= link_to "Reservations", "/users/#{r.id}/reserve" %><br>
	<%=link_to "Edit Restaurant", edit_restaurant_path(r) %> | <%=link_to "Delete Restaurant", restaurant_path(r), :confirm => "Delete?", :method => :delete %></li>
	<% end %>
	<li> <p> <%= link_to "Add a new restaurant", new_restaurant_path, class: "button radius" %> </p> </li>
	</ul>

 
	
<% end %>

	
<% if current_user.categories.find{|c| c[:text]=="ruser"} %>
	<p> Add reservation to one of the restaurants below: </p>
	<% @restaurants.each do |r| %>
	<%=r.name %> | <%=r.opentime %>-----<%= r.closetime %> | Number of seats: <%=r.totalsize %> | <%= r.address%> <br>
	<%= link_to "Menu - Order Online", "/restaurants/#{r.id}/#{r.menus.last.id}" unless r.menus.last==nil%><br>

	Dates available: 
		<% r.moments.each do |m| %>
	        <%=m.date%><br>

	        

  			<% m.slots.each do |time| %>
    			<%= time.tock.strftime("%H:%M") %> = <%=time.seats%><br>
  			<% end %><br><br>
		<% end %>
		<%= link_to "Make a reservation", "/users/#{current_user.id}/join/#{r.id}" %> || <%= link_to "Or rate this place", "/users/#{current_user.id}/#{r.id}/rate" %> <br>

	Rating by <%= r.raters %> customers is: <%=r.rating %> out of a possible 5 <br>
	<% end %><br> 
	


	
	My Reservatons: <br>
	<% @reservations.each do |rev| %>
	<%= Restaurant.find_by_id(rev.restaurant_id).name %> on <%=rev.day%> at <%=rev.hour %> for <%=rev.numberofseats%> | <%=link_to "Delete", user_reservation_path(current_user,rev), :confirm => "Delete?", :method => :delete %><br><br>
	<% Restaurant.find_by_id(rev.restaurant_id).moments.each do |m| %>
	        <%=m.date%><br>

  			<% m.slots.each do |time| %>
    			<%= time.tock.strftime("%H:%M") %> = <%=time.seats%><br>
  			<% end %><br><br>
		<% end %>
	<% end %> 

<% end %>


<!-- should refactor to only display restaurants that are not in the reservations in controller -->