config/routes.rb
Seatyourself::Application.routes.draw do
  get "users/new"
  get "users/edit"
  get "users/show"
  get "welcome_path" => "welcome#index"
  get '/users/:user_id/join/:id' => "users#joinnew"
  resources :sessions
  root "welcome#index"
  resources :users do
    resources :categories 
    resources :reservations
  end
  resources :restaurants do
    resources :moments
    resources :menus
  end
  resources :menus do
    resources :items
  end

  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
  get '/sessions' => 'sessions#create'

  match '/users/:user_id/join/:id', to: "users#joinnew", via: [:get,:post]
  get '/users/:user_id/:restaurants_id/rate' => "restaurants#rate"
  get "/users/:id/time" => "restaurants#index"
  get "/users/:id/reserve" => "restaurants#reserve"
  get "/users/:user_id/:restaurant_id/:menu_id/:item_id" => "orders#create"
  get "/restaurants/:restaurant_id/:menu_id"=> "menus#show"
  get "/remove/:restaurant_id/:menu_id/:order_id/:id" => "orders#remove"
  

  

end

app/models/category.rb
class Category < ActiveRecord::Base
	belongs_to :user
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :menu
	belongs_to :order
	belongs_to :user
	belongs_to :restaurant
end

app/models/menu.rb
class Menu < ActiveRecord::Base
	belongs_to :restaurant
	has_many :items
	has_many :orders
end

app/models/moment.rb
class Moment < ActiveRecord::Base
	belongs_to :restaurant
	has_many :slots
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	has_many :items
	belongs_to :restaurant
	belongs_to :menu
	
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :restaurant
	belongs_to :user
	#validates :betweenhours

	def betweenhours
		Reservation.find_by_id(params[:id])
	end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :reservations
	has_many :users, :through=> :reservations
	has_many :moments
	has_many :slots, through: :moments
    has_many :menus
    has_many :items, :through => :menus
    has_many :orders
    has_many :items, :through => :orders

	def to_datetime(t)
    # Convert seconds + microseconds into a fractional number of seconds
    	seconds = sec + Rational(t.sec, 10**6)

    # Convert a UTC offset measured in minutes to one measured in a
    # fraction of a day.
    	offset = Rational(t.utc_offset, 60 * 60 * 24)
    	DateTime.new(year, month, day, hour, min, seconds, offset)
  end
end

app/models/slot.rb
class Slot < ActiveRecord::Base
	belongs_to :moment
	def to_datetime(t)
    # Convert seconds + microseconds into a fractional number of seconds
    	seconds = sec + Rational(t.sec, 10**6)

    # Convert a UTC offset measured in minutes to one measured in a
    # fraction of a day.
    	offset = Rational(t.utc_offset, 60 * 60 * 24)
    	DateTime.new(year, month, day, hour, min, seconds, offset)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :categories
	has_many :reservations
	has_many :restaurants, :through=> :reservations
	has_many :orders
	has_many :items, :through=> :orders
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/moments_helper.rb
module MomentsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
require 'date'

module RestaurantsHelper
class Time
  def to_datetime
    # Convert seconds + microseconds into a fractional number of seconds
    seconds = sec + Rational(usec, 10**6)

    # Convert a UTC offset measured in minutes to one measured in a
    # fraction of a day.
    offset = Rational(utc_offset, 60 * 60 * 24)
    DateTime.new(year, month, day, hour, min, seconds, offset)
  end
end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "SuperSeat" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="large-12 large-centered columns">

    <% if current_user %>
  Welcome <%= User.find_by_id(current_user).name %> || <%= link_to "Sign out", signout_path, id: "sign_out" %> || <%= link_to "Your Profile", user_path(User.find_by_id(current_user)) %> || 
  
<% else %>
   <%= link_to "Sign in without Facebook", new_session_path %> || <%= link_to "Sign up without Facebook", new_user_path %>
<% end %>


    <%= yield %>

    
    <%= javascript_include_tag "application" %>
  </div>
  </body>
</html>